

// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Command.

package frc.robot.commands;
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.PS4Controller;
import edu.wpi.first.wpilibj2.command.CommandBase;
import frc.robot.RobotContainer;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import frc.robot.subsystems.DriveSubsystem;
import frc.robot.subsystems.IntakeSubsystem;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


public class IntakeCommand extends CommandBase {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
        private final IntakeSubsystem m_IntakeSubsystem;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

    //variables for l1 reset and x abort
    boolean isResetDown = false;
    boolean L1WasPressed = false;
    boolean isResetUp = false;
    boolean R1WasPressed = false;
    private DigitalInput intakeLowerLimit;
    private DigitalInput intakeUpperLimit;


    public IntakeCommand(IntakeSubsystem subsystem) {
        //define switches           
        intakeLowerLimit = new DigitalInput(1);
        intakeUpperLimit = new DigitalInput(2);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        m_IntakeSubsystem = subsystem;
        addRequirements(m_IntakeSubsystem);

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called when the command is initially scheduled.
    @Override
    public void initialize() {
        //put the arm in starting position(up)
        //m_IntakeSubsystem.getMotorGroup()

    }

    // Called every time the scheduler runs while the command is scheduled.
    @Override
    public void execute() {
        PS4Controller controller = RobotContainer.getInstance().getPS4DriveController();
        if (controller.getSquareButtonPressed())
            m_IntakeSubsystem.intakeIn();
        if (controller.getCrossButtonPressed())
            m_IntakeSubsystem.intakeOff();
        if (controller.getTriangleButtonPressed())
            m_IntakeSubsystem.intakeOut();
        if (controller.getCircleButtonPressed())
            m_IntakeSubsystem.liftOff();

        if (controller.getL2Axis() > 0.01)
            m_IntakeSubsystem.liftDown(controller.getL2Axis());
        else if (controller.getR2Axis() > 0.01)
            m_IntakeSubsystem.liftUp(controller.getR2Axis());
        else
            m_IntakeSubsystem.liftOff();

        //pressing R1 turns off intake and brings arm up
        if (controller.getR1Button())
            R1WasPressed = true;
            m_IntakeSubsystem.intakeOff();
        if (R1WasPressed)
            m_IntakeSubsystem.liftUp(Math.sqrt(.5)); //move motor down
        if (intakeUpperLimit.get() || controller.getCrossButtonPressed()){ //if switch is touched 
            R1WasPressed = false;
            isResetUp = true;
        }
        if (R1WasPressed == false && isResetUp == true) {
            m_IntakeSubsystem.liftOff();//stop motor
            isResetUp = false;
        }

        //pressing L1 button brings arm down and turns on intake
        if (controller.getL1Button())
            L1WasPressed = true;
            m_IntakeSubsystem.intakeIn();
        if (L1WasPressed)
            m_IntakeSubsystem.liftDown(Math.sqrt(.5)); //move motor down
        if (intakeLowerLimit.get() || controller.getCrossButtonPressed()){ //if switch is touched 
            L1WasPressed = false;
            isResetDown = true;
        }
        if (L1WasPressed == false && isResetDown == true) {
            m_IntakeSubsystem.liftOff();//stop motor
            isResetDown = false;
        }


            
            
    }

    // Called once the command ends or is interrupted.
    @Override
    public void end(boolean interrupted) {
    }

    // Returns true when the command should end.
    @Override
    public boolean isFinished() {
        return false;
    }

    @Override
    public boolean runsWhenDisabled() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
        return false;

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
    }
}


