// Copyright (c) FIRST and other WPILib contributors.
// Open Source Software; you can modify and/or share it under the terms of
// the WPILib BSD license file in the root directory of this project.

package frc.robot.subsystems;

import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import frc.robot.commands.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj2.command.SubsystemBase;

import com.revrobotics.CANSparkMax;
import com.revrobotics.RelativeEncoder;
import com.revrobotics.SparkMaxPIDController;
import com.revrobotics.CANSparkMax.ControlType;
import com.revrobotics.CANSparkMax.IdleMode;
import com.revrobotics.CANSparkMaxLowLevel.MotorType;

import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.Timer;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.drive.DifferentialDrive;
import edu.wpi.first.wpilibj.motorcontrol.MotorController;
import edu.wpi.first.wpilibj.motorcontrol.MotorControllerGroup;
import edu.wpi.first.wpilibj.motorcontrol.Spark;
import edu.wpi.first.wpilibj.motorcontrol.VictorSP;

public class IntakeSubsystem extends SubsystemBase {
  private CANSparkMax linkageMotor;
  private VictorSP intake;
  private MotorControllerGroup liftMotorControllerGroup;
  private DigitalInput intakeLowerLimit;
  //private DigitalInput intakeUpperLimit;
  private boolean holdLiftPos = false;
  private boolean startingPositionConfigured = false;
  private boolean encoderResetToLowerLimit = false;

  //pid controller stuff
  private SparkMaxPIDController m_pidController;
  public double kP, kI, kD, kIz, kFF, kMaxOutput, kMinOutput;

  private static double upperLimit = 25;

  private enum IntakeDirection { Off, In, Out};

  private IntakeDirection intakeDirection = IntakeDirection.Off;

  private double lastDashboardUpdateTime = Timer.getFPGATimestamp();

  private double intakeStartTime = -1;

  public IntakeSubsystem() {
    linkageMotor = new CANSparkMax(15, MotorType.kBrushless);
    linkageMotor.setInverted(true);
    linkageMotor.setIdleMode(IdleMode.kBrake);

    intakeLowerLimit = new DigitalInput(3);
    //intakeUpperLimit = new DigitalInput(4);

    // liftMotorRight = new CANSparkMax(16, MotorType.kBrushless);
    // liftMotorRight.setInverted(false);

    // liftMotorControllerGroup = new MotorControllerGroup(liftMotorLeft, liftMotorRight);
    
    intake = new VictorSP(0);
    intake.setInverted(false);


    //pid controller stuff
    m_pidController = linkageMotor.getPIDController();

    // PID coefficients
    kP = 0.1; 
    kI = 1e-4;
    kD = 1; 
    kIz = 0; 
    kFF = 0; 
    kMaxOutput = 1; 
    kMinOutput = -1;

    // set PID coefficients
    m_pidController.setP(kP);
    m_pidController.setI(kI);
    m_pidController.setD(kD);
    m_pidController.setIZone(kIz);
    m_pidController.setFF(kFF);
    m_pidController.setOutputRange(kMinOutput, kMaxOutput);

    // Reset encoder
    //RelativeEncoder encoder = linkageMotor.getEncoder();
    //encoder.setPosition(0);

    // display PID coefficients on SmartDashboard
    /*SmartDashboard.putNumber("P Gain", kP);
    SmartDashboard.putNumber("I Gain", kI);
    SmartDashboard.putNumber("D Gain", kD);
    SmartDashboard.putNumber("I Zone", kIz);
    SmartDashboard.putNumber("Feed Forward", kFF);
    SmartDashboard.putNumber("Max Output", kMaxOutput);
    SmartDashboard.putNumber("Min Output", kMinOutput);
    SmartDashboard.putNumber("Set Rotations", linkageMotor.getEncoder().getPosition());*/
    SmartDashboard.putNumber("Intake Linkage Position", linkageMotor.getEncoder().getPosition());
    SmartDashboard.putBoolean("Starting Position Configured", startingPositionConfigured);
    SmartDashboard.putBoolean("Encoder Reset To Lower Limit", encoderResetToLowerLimit);
    SmartDashboard.putString("Intake Mode", intakeDirection.toString());
  }

  @Override
  public void periodic() {
    // This method will be called once per scheduler run
    // read PID coefficients from SmartDashboard
    /*double p = SmartDashboard.getNumber("P Gain", 0);
    double i = SmartDashboard.getNumber("I Gain", 0);
    double d = SmartDashboard.getNumber("D Gain", 0);
    double iz = SmartDashboard.getNumber("I Zone", 0);
    double ff = SmartDashboard.getNumber("Feed Forward", 0);
    double max = SmartDashboard.getNumber("Max Output", 0);
    double min = SmartDashboard.getNumber("Min Output", 0);
    double rotations = SmartDashboard.getNumber("Set Rotations", 0);*/

    if (Timer.getFPGATimestamp() - lastDashboardUpdateTime > 1)
    {
      SmartDashboard.putNumber("Intake Linkage Position", linkageMotor.getEncoder().getPosition());
      SmartDashboard.putString("Intake Mode", intakeDirection.toString());
      SmartDashboard.putBoolean("Starting Position Configured", startingPositionConfigured);
      SmartDashboard.putBoolean("Encoder Reset To Lower Limit", encoderResetToLowerLimit);
      SmartDashboard.putBoolean("At Intake Lower Limit", atLowerLimit());
      SmartDashboard.putBoolean("At Intake Upper Limit", atUpperLimit());
      lastDashboardUpdateTime = Timer.getFPGATimestamp();
    }

    // if PID coefficients on SmartDashboard have changed, write new values to controller
    /*if((p != kP)) { m_pidController.setP(p); kP = p; }
    if((i != kI)) { m_pidController.setI(i); kI = i; }
    if((d != kD)) { m_pidController.setD(d); kD = d; }
    if((iz != kIz)) { m_pidController.setIZone(iz); kIz = iz; }
    if((ff != kFF)) { m_pidController.setFF(ff); kFF = ff; }
    if((max != kMaxOutput) || (min != kMinOutput)) { 
      m_pidController.setOutputRange(min, max); 
      kMinOutput = min; kMaxOutput = max; 
    }*/

    //PIDController objects are commanded to a set point using the SetReference() method.
    //m_pidController.setReference(rotations, CANSparkMax.ControlType.kPosition);
    
    if (atLowerLimit())
    {
      // Reset the encoder to 0 since we're at the intake lower limit
      linkageMotor.getEncoder().setPosition(0);
      linkageMotor.getPIDController().setReference(0, ControlType.kPosition);
      encoderResetToLowerLimit = true;
    }

    // Do we need to configure the starting position?
    if (false == startingPositionConfigured)
    {
      linkageMotor.setIdleMode(IdleMode.kCoast);

      // Reset the starting position
      if (encoderResetToLowerLimit)
      {
        // Starting position has been configured. Wait until a student has lifted
        // the intake into position and lock it there
        if (linkageMotor.getEncoder().getPosition() >= (upperLimit - 2))
        {
          linkageMotor.setIdleMode(IdleMode.kBrake);
          holdLiftPosition();
          startingPositionConfigured = true;
        }
      }
    }

    // automatically turn off intake
    if (Timer.getFPGATimestamp() - intakeStartTime > 3)
    {
      intakeOff();
    }
  }

  @Override
  public void simulationPeriodic() {
    // This method will be called once per scheduler run during simulation
  }

  
  public void intakeIn(){
    intakeStartTime = Timer.getFPGATimestamp();
    intake.set(-1);
    intakeDirection = IntakeDirection.In;
  }
  
  public void intakeOff(){
    intake.set(0);
    intakeDirection = IntakeDirection.Off;
    intakeStartTime = -1;
  }

  public void intakeOut(){
    intakeStartTime = Timer.getFPGATimestamp();
    intake.set(1);
    intakeDirection = IntakeDirection.Out;
  }

  public void liftOff(){
    linkageMotor.set(0);
  }

  public void holdLiftPosition()
  {
    if (!holdLiftPos)
    {
      liftOff();
      holdLiftPos = true;
      double curPosition = linkageMotor.getEncoder().getPosition();
      linkageMotor.getPIDController().setReference(curPosition, ControlType.kPosition);
      
      SmartDashboard.putNumber("Intake Linkage Position", curPosition);
    }
  }

  public boolean atLowerLimit() {
    return !intakeLowerLimit.get();
  }

  public void liftDown(double power){
    if (atLowerLimit())
    {
      holdLiftPosition();
    }
    else
    {
      holdLiftPos = false;
      double adjustedPower = Math.max(-power * power, -0.2);
      linkageMotor.set(adjustedPower);
    }
  }

  public boolean atUpperLimit()
  {
    return encoderResetToLowerLimit && linkageMotor.getEncoder().getPosition() > upperLimit;
  }

  public void liftUp(double power){
    if (atUpperLimit())
    {
      holdLiftPosition();
    }
    else
    {
      holdLiftPos = false;
      double adjustedPower = Math.min(power * power, 0.3);
      linkageMotor.set(adjustedPower);
    }
  }

  /*
  public void armDownAndIntakeOn(){
    // TODO use encoders to bring it down
    // TODO start intake
    intakeIn();
    if (!intakeLowerLimit.get()){
      linkageMotor.set(-0.5);
    } else {
      linkageMotor.set(0);
    }

  }

  public void armUpAndIntakeOff(){
    // TODO off intake
    // TODO use encoders to bring it up
    intakeOff();
    if (!intakeUpperLimit.get()){
      linkageMotor.set(0.5);
    } else {
      linkageMotor.set(0);
    }

  }
  */

}
